config/routes.rb
Games::Application.routes.draw do

  resources :tic_tac_toe_games do 
    resources :ttt_moves 
  end
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  post '/tic_tac_toe_games/:tic_tac_toe_game_id/ttt_moves', to: 'ttt_moves#create', as: 'create_tic_tac_toe_game_ttt_move'
  post '/tic_tac_toe_games/', to: 'tic_tac_toe_games#create', as: 'create_tic_tac_toe_game'
  root to: 'application#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  

rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, :alert => exception.message
end

def index
  @games = TicTacToeGame.recent_games(session[:user_id])
  @games_count = TicTacToeGame.games_count(session[:user_id])
end

helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  private
  def authenticate
    unless logged_in?
      flash[:error] = "You must be logged in to access this section of the site"
      redirect_to new_session_path
    end
  end

helper_method :set_computer_user 
  def set_computer_user
    User.find_by_username('Computer')
  end


end

app/helpers/application_helper.rb
 module ApplicationHelper

  def board_move(game, x_coord, y_coord)
    move = game.ttt_moves.select do |move| move.x_coordinate == x_coord && move.y_coordinate == y_coord end
    if move.any?
      move[0].make_x_or_o?(image_tag('circle-x-8x.png', class: "x-play"), image_tag('media-record-8x.png', class: "o-play"))
    elsif game.continue? && session[:user_id] == game.user_turn_id
      link_to image_tag(game.x_or_o_next?('circle-x-8x.png', 'media-record-8x.png'), class: "next-play #{game.x_or_o_next?('x-play', 'o-play')}"), create_tic_tac_toe_game_ttt_move_path(game.id, x_coord: "#{x_coord}", y_coord: "#{y_coord}"), method: :post
    else
      " "
    end
  end



end

app/views/application/index.html.erb
<h1>Games</h1>
<section class='game_display'>
  <div class='game-head'>
    <h2 class='heading'>Tic-Tac-Toe</h2>
    <%= image_tag('tic-tac-toe-board.png', class: 'home') %>
  </div>
  <p class='home'><%= link_to 'New One Player Game', new_tic_tac_toe_game_path(game_type: "single"), method: :get, class: 'new_game' %>
  <%= link_to 'New Two Player Game', new_tic_tac_toe_game_path(game_type: "dual"), method: :get, class: 'new_game' %>
  <% @games.each do |opponent, game| %>
    <%= link_to "Continue Game vs: #{opponent[0].username}", tic_tac_toe_game_path(game.id) %>
  <% end %>
    </p>
  <% if @games_count > @games.length %>
    <%= link_to "more ongoing games...", user_path(current_user.id), class: 'more_games' %>
  <% end %>
</section>