config/routes.rb
Games::Application.routes.draw do

  resources :tic_tac_toe_games do 
    resources :ttt_moves 
  end
  resources :users, only: [:index, :new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  post '/tic_tac_toe_games/:tic_tac_toe_game_id/ttt_moves', to: 'ttt_moves#create', as: 'create_tic_tac_toe_game_ttt_move'
  post '/tic_tac_toe_games/', to: 'tic_tac_toe_games#create', as: 'create_tic_tac_toe_game'
  root to: 'application#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <%= yield :head %>
</head>
<body>
  <% flash.each do |name, message| %>
    <div class="flash-message flash-message-<%= name %>">
      <p><%= message %></p>
    </div>
  <% end %>
  <header>
    <div class='float-right'>
      <% if current_user %>
        <h4> what's up, <%= link_to current_user.username, user_path(current_user.id) %></h4>
        <h4><%= link_to 'Logout', session_path(session), method: :delete %></h4>
      <% else %>
        <h4><%= link_to 'Login', new_session_path %> </h4>
        <h4><%= link_to 'Create Account', new_user_path %></h4>
      <% end %>
    </div>
    <h4 class='float-left'><%= link_to 'Main Menu', root_path %></h4>
  </header>




<%= yield %>

</body>
</html>